export const ROLES = {
  'Frontend developer': [
    'HTML',
    'CSS',
    'JavaScript',
    'React',
    'TypeScript',
    'Tailwind CSS',
    'Testing',
    'Git',
  ],
  'Backend developer': [
    'Node.js',
    'Express',
    'REST APIs',
    'MongoDB',
    'SQL',
    'Authentication',
    'Testing',
    'Docker',
  ],
  'Full-stack developer': [
    'React',
    'Node.js',
    'Express',
    'MongoDB',
    'REST APIs',
    'Git',
    'Testing',
    'Docker',
  ],
  'AI engineer': [
    'Python',
    'JavaScript',
    'LLM APIs',
    'Prompt engineering',
    'RAG',
    'Vector databases',
    'Evaluation',
    'Node.js',
  ],
}
